### ISSUE TITLE
Marked abandoned

### ISSUE THREAD

**Issue by luceos** [XEngine/flarum-markdown-editor#13]
Hello @XEngine ,

Your extension seems to be no longer compatible with the latest Flarum version(s). As such I've marked it abandoned on our official forums. Feel free to respond over there or contact a moderator to unmark it as such when the extension is again compatible.

https://discuss.flarum.org/d/4075-simplemde-for-flarum

Thank you,

Daniël, on behalf of the Flarum team.

**Comment by ghost** [comment]
@luceos I am testing this extension right now, and it still seems to work.....

**Comment by XEngine** [comment]
I have no time to maintain this extension anymore because of life. Even it works in current versions, it may not in newer versions.

**Comment by ghost** [comment]
@XEngine ok, I may fork this and revive it but I am not sure yet
