### ISSUE TITLE
Can't download the extension via composer

### ISSUE THREAD

**Issue by thoomson** [XEngine/flarum-markdown-editor#14]
Hi,

I have a little problem. When I enter this command in my Putty terminal : 
`composer require extum/flarum-ext-markdown-editor`

I have this answer : 
```
[InvalidArgumentException]
Could not find package extum/flarum-ext-markdown-editor at any version for your minimum-stability (beta). Check the package spelling or your minimum-stability
```

Do you have an idea why?

Thank you very much for you work.
Antoine

**Comment by ardacebi** [comment]
Hi Antoine,

This extension has been recently transferred from a single developer to the Extum organization. We haven't released any stable versions of this extensions yet, but if you want to use the Beta version of the extension until it's released by us, please execute the following command on your Flarum installation directory:

`composer require extum/flarum-ext-markdown-editor:dev-master`

Let me know when the issue gets fixed.

**Comment by thoomson** [comment]
Thank you so much !

Have a nice day :)
