### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by jtojnar** [XEngine/flarum-markdown-editor#6]
The editor behaves strangely:

https://gfycat.com/GrossEnchantingHuemul

Looks like problems with virtual dom – does Flarum use it?

**Comment by darkcyber** [comment]
+1 this bug seems valid
and one more again
format icon is not working like expected if you select word then select format icon (bold).
you need to give it space or some change in text editor to make it change (look in preview)
maybe you can try it @jtojnar
